version: '3.8'

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/teqqed
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev # Use "npm start" if you want to run in production mode

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: teqqed
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: